name: CI Build

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ch007m/fork-kindcontainer.git
          ref: enable-featuregate

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: 'gradle'

      - name: Build kindcontainer testcontainer project
        run: |
          gradle publishToMavenLocal

      - uses: guillermocalvo/gradle-properties@v3
        id: properties
        with:
          output_file: ${{ github.output }}

      - run: |
          echo Project name: ${{ steps.properties.outputs.name }}
          echo Project version: ${{ steps.properties.outputs.version }}

      - uses: actions/checkout@v4
        with:
          repository: quarkiverse/quarkus-argocd.git
          ref: main

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: 'maven

      - name: Build quarkus-argocd as not yet released with Maven
        run: |
          mvn -B clean install -Dno-format -DskipTests    

      - uses: actions/checkout@v4

      - name: Build this project
        run: |
          mvn -B clean install -Dno-format -DskipTests -Dquarkus-argocd.version="999-SNAPSHOT"

      - name: Perform CI test
        run: |
          export TESTCONTAINERS_RYUK_DISABLED=true
          mvn test -Dtest=ArgoCDDeployTest