name: CI Build

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Remove old executables
        run: |
          # Remove the old crun executable to let brew to install a newer one ...
          sudo apt-get remove crun

      - name: Install podman and show dependencies
        run: |
          # What brew will install: https://ghcr.io/v2/homebrew/core/podman/manifests/5.3.1_1
          brew install podman
          brew services start podman

      - name: Check podman and crun versions
        run: |
          podman -v
          crun -v

      - uses: actions/checkout@v4
        with:
          repository: ch007m/fork-kindcontainer.git
          ref: enable-featuregate

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build kindcontainer testcontainer project
        run: |
          gradle publishToMavenLocal

      - uses: guillermocalvo/gradle-properties@v3
        id: properties
        with:
          output_file: ${{ github.output }}

      - run: |
          echo Project name: ${{ steps.properties.outputs.name }}
          echo Project version: ${{ steps.properties.outputs.version }}

      - uses: actions/checkout@v4
        with:
          repository: quarkiverse/quarkus-argocd.git
          ref: main

      - name: Build quarkus-argocd as not yet released with Maven
        run: |
          mvn -B clean install -Dno-format -DskipTests    

      - uses: actions/checkout@v4

      - name: Build this project
        run: |
          ls -la ~/.m2/repository/com/dajudge/kindcontainer/kindcontainer
          ls -la ~/.m2/repository/io/quarkiverse/argocd/quarkus-argocd-deployment
          mvn -B clean install \
            -Dno-format \
            -DskipTests \
            -Dquarkus-argocd.version="999-SNAPSHOT" \
            -Dtestcontainer.version=${{ steps.properties.outputs.version }}

      - name: Perform CI test
        run: |
          export TESTCONTAINERS_RYUK_DISABLED=true
          export DOCKER_HOST="unix:///var/run/docker.sock"
          mvn test -Dtest=ArgoCDDeployTest