name: CI Build

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Remove old executable of crun and stop docker service
        run: |
          # Remove the old crun executable to let brew to install a newer one ...
          sudo apt-get remove crun
          sudo systemctl stop docker.socket
          sudo systemctl stop docker

      - name: Install podman v5 using homebrew
        run: |
          # What brew will install: https://ghcr.io/v2/homebrew/core/podman/manifests/5.3.1_1
          brew install podman
          brew services start podman

      - name: Check podman and crun versions
        run: |
          podman -v
          crun -v
          podman system service --time=0 &
          systemctl --user enable --now podman.socket
          ls $XDG_RUNTIME_DIR/podman/podman.sock

      - name: Check podman sock
        run: |
          podman info | grep sock
          
          podman info | grep root

          echo $(id -u)
          
          ls -la ${XDG_RUNTIME_DIR}/podman/podman.sock

      - uses: actions/checkout@v4
        with:
          repository: ch007m/fork-kindcontainer.git
          ref: enable-featuregate

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build kindcontainer testcontainer project
        id: build-kindcontainer
        run: |
          export SNAPSHOT_VERSION=$(gradle publishToMavenLocal --console=plain | grep 'Publishing to maven local' | awk -F':' '{print $NF}')
          echo "SNAPSHOT_VERSION=$SNAPSHOT_VERSION" >> "$GITHUB_OUTPUT"

      - run: |
          echo Snapshot version of kind container: ${{ steps.build-kindcontainer.outputs.SNAPSHOT_VERSION }}

      - uses: actions/checkout@v4
        with:
          repository: quarkiverse/quarkus-argocd.git
          ref: main

      - name: Build quarkus-argocd as not yet released with Maven
        run: |
          mvn -B clean install -Dno-format -DskipTests    

      - uses: actions/checkout@v4

      - name: Build this project
        run: |
          mvn -B clean install \
            -Dno-format \
            -DskipTests \
            -Dquarkus-argocd.version="999-SNAPSHOT" \
            -Dtestcontainer.version=${{ steps.build-kindcontainer.outputs.SNAPSHOT_VERSION }}

      - name: Perform CI test
        run: |
          export TESTCONTAINERS_RYUK_DISABLED=true
          export DOCKER_HOST="unix://${XDG_RUNTIME_DIR}/podman/podman.sock"
          #export DOCKER_HOST="unix:///usr/lib/systemd/user/podman.socket"
          mvn -B test -Dtest=ArgoCDDeployTest \
            -Dquarkus-argocd.version="999-SNAPSHOT" \
            -Dtestcontainer.version=${{ steps.build-kindcontainer.outputs.SNAPSHOT_VERSION }}