name: CI Build

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-13, ubuntu-latest]
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - if: matrix.os == 'ubuntu-latest'
        name: Remove old executable of crun and stop docker service
        run: |
          # Remove the old crun executable to let brew to install a newer one ...
          sudo apt-get remove crun
          sudo systemctl stop docker.socket
          sudo systemctl stop docker

      - name: Install podman v5 using homebrew
        run: |
          # What brew will install: https://ghcr.io/v2/homebrew/core/podman/manifests/5.3.1_1
          brew install podman
          brew services start podman

      - name: Create linux's vm on macos
        if: matrix.os == 'macos-13'
        run: |
          podman machine init
          podman machine start --log-level debug

      - name: Expose the podman API and podman.socket
        if: matrix.os == 'ubuntu-latest'
        run: |
          podman system service --time=0 &
          systemctl --user enable --now podman.socket

      - name: Podman information
        run: |
          echo "Podman version: " $(podman info -f json | jq -r .version.Version)
          echo "Podman rootless: " $(podman info -f json | jq -r .host.security.rootless)
          echo "Podman sock path: " $(podman info -f json | jq -r .host.remoteSocket.path)

      - name: Podman service status on Linux
        if: matrix.os == 'ubuntu-latest'
        run: |  
          systemctl status podman &
          systemctl --user status podman.socket &

      - uses: actions/checkout@v4
        with:
          repository: ch007m/fork-kindcontainer.git
          ref: enable-featuregate

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build kindcontainer testcontainer project
        id: build-kindcontainer
        run: |
          export SNAPSHOT_VERSION=$(gradle publishToMavenLocal --console=plain | grep 'Publishing to maven local' | awk -F':' '{print $NF}')
          echo "SNAPSHOT_VERSION=$SNAPSHOT_VERSION" >> "$GITHUB_OUTPUT"

      - run: |
          echo Snapshot version of kind container: ${{ steps.build-kindcontainer.outputs.SNAPSHOT_VERSION }}

      - uses: actions/checkout@v4
        with:
          repository: quarkiverse/quarkus-argocd.git
          ref: main

      - name: Build quarkus-argocd as not yet released with Maven
        run: |
          mvn -B clean install -Dno-format -DskipTests    

      - uses: actions/checkout@v4

      - name: Build this project
        run: |
          mvn -B clean install \
            -Dno-format \
            -DskipTests \
            -Dquarkus-argocd.version="999-SNAPSHOT" \
            -Dtestcontainer.version=${{ steps.build-kindcontainer.outputs.SNAPSHOT_VERSION }}

      - name: Perform CI test
        run: |
          export TESTCONTAINERS_RYUK_DISABLED=true
          export DOCKER_HOST="unix://${XDG_RUNTIME_DIR}/podman/podman.sock"

          mvn -B test -Dtest=ArgoCDDeployTest \
            -Dquarkus-argocd.version="999-SNAPSHOT" \
            -Dtestcontainer.version=${{ steps.build-kindcontainer.outputs.SNAPSHOT_VERSION }}